"use client";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SideNavbar } from "./Components/SideBar/page";
import { NavBar } from "./Components/NavBar/page";
import { useSearchParams } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const searchParams = useSearchParams();
  const search = searchParams.get("companyName");
  return (
    <html lang="en">
      <body className={inter.className}>
        {search ? (
          <NextUIProvider>
            <main className="mytheme text-foreground overflow-hidden p-4">
              <div className="flex flex-row">
                <div className="w-1/4 md:w-1/3 lg:w-1/5">
                  <SideNavbar />
                </div>
                <div className="w-1/4 md:w-2/3 lg:w-4/5 px-3 custom-scrollbar">
                  <NavBar />
                  <div className="navBarStyle p-4 mt-3">{children}</div>
                </div>
              </div>
            </main>
          </NextUIProvider>
        ) : (
          <div
            style={{
              height: "100vh",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <a href="http://localhost:3000">
              <button style={{background : "white", padding: "14px", borderRadius : "10px"}}>Please login or register our company</button>
            </a>
          </div>
        )}
      </body>
    </html>
  );
}
